### ISSUE TITLE
compatibility issue

### ISSUE THREAD

**Issue by Wettix** [EmosewaPixel/GregicAdditions#3] opened 2018-09-26 11:51 UTC
Advanced generator is quite simply no compatibility with gregic additions
after,
draconic evolution, endercore, ender io, exchanger causing crash with gregic addition with this mod list : 

![ss 2018-09-26 at 01 40 14](https://user-images.githubusercontent.com/43379174/46077603-c4bdec80-c191-11e8-85a1-326c26e506ea.png)

but with only GTCE gregic addition and GTCE bees i have no crash with these mods, i share that for helping you to fix that, i don't know who is the mod is no compatible with draconic, endercore/io, exchangeur when gregic addition is on the pack, but in crash log gregic addition is the cause

[crash log with draconic, brandon's core] 
[crash-2018-09-26_13.45.36-client.txt](https://github.com/EmosewaPixel/GregicAdditions/files/2419527/crash-2018-09-26_13.45.36-client.txt)

[crash log with endercore/io] 
[crash-2018-09-26_13.49.37-client.txt](https://github.com/EmosewaPixel/GregicAdditions/files/2419529/crash-2018-09-26_13.49.37-client.txt)

**Comment by EmosewaPixel** [comment] 2018-09-27 17:56
Duplicate of #1

**Closed by EmosewaPixel** 2018-09-27 17:56 UTC
Labels: duplicate
