### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by Rongmario** [EmosewaPixel/GregicAdditions#7] opened 2018-10-01 06:19 UTC
https://paste.dimdev.org/xememajuye.mccrash

**Comment by EmosewaPixel** [comment] 2018-10-01 06:37
Duplicate of #1

**Closed** 2018-10-01 06:37 UTC
Labels: duplicate

**Comment by Rongmario** [comment] 2018-10-01 07:15
No, it's duplicate of #4 not #1

**Comment by EmosewaPixel** [comment] 2018-10-01 07:16
Well, both.
