### ISSUE TITLE
Crash with IC2classic

### ISSUE THREAD

**Issue by DbpGaming** [EmosewaPixel/GregicAdditions#2] opened 2018-09-25 22:00 UTC
https://pastebin.com/m5QrG7SH
don't know what to say about this Agrax also seems to be having a similar crash without ic2classic, but the only mods that are consistent between us are this and GTCE it self

**Comment by EmosewaPixel** [comment] 2018-09-27 17:55
Duplicate of #1

**Closed by EmosewaPixel** 2018-09-27 17:55 UTC
Labels: duplicate
