### ISSUE TITLE
found a bug between gregic additions and heat and climate bug

### ISSUE THREAD

**Issue by utoc123** [EmosewaPixel/GregicAdditions#38] opened 2018-12-08 04:34 UTC
java.lang.ClassCastException: gregtech.api.unification.material.type.IngotMaterial cannot be cast to gregtech.api.unification.material.type.GemMaterial
    at gregicadditions.item.GAMetaTool.registerRecipes(GAMetaTool.java:53)
    at gregicadditions.item.GAMetaItems.registerRecipes(GAMetaItems.java:147)
    at gregicadditions.CommonProxy.registerRecipes(CommonProxy.java:66)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_22_CommonProxy_registerRecipes_Register.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:787)
    at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:624)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
    at net.minecraft.client.Minecraft.init(Minecraft.java:535)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by EmosewaPixel** [comment] 2019-01-02 13:57
The crash has nothing to do with that mod. This is a duplicate of #39

**Closed by EmosewaPixel** 2019-01-02 13:57 UTC
