### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by G1R-Productions** [EmosewaPixel/GregicAdditions#6] opened 2018-09-28 16:16 UTC
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  ForgelinPlugin (Forgelin-1.7.4.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-85.jar)
  FMLModule ([1.12.2][3.0.0.3] mdxlib.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.16.jar)
  DLFMLCorePlugin (DynamicLights-1.12.2.jar)
  llibrary (llibrary-core-1.0.8-1.12.2.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 9/29/18 12:13 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Gregic Additions (gtadditions)
Caused by: java.lang.NullPointerException: Null string not allowed
	at java.util.Objects.requireNonNull(Objects.java:228)
	at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:19)
	at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:137)
	at net.minecraftforge.fluids.FluidStack.writeToNBT(FluidStack.java:107)
	at net.minecraftforge.fluids.capability.templates.FluidHandlerItemStackSimple.setFluid(FluidHandlerItemStackSimple.java:86)
	at net.minecraftforge.fluids.capability.templates.FluidHandlerItemStackSimple.fill(FluidHandlerItemStackSimple.java:112)
	at gregicadditions.item.GAMetaItems.getFilledCell(GAMetaItems.java:137)
	at gregicadditions.recipes.GARecipeAddition.postInit(GARecipeAddition.java:1061)
	at gregicadditions.GregicAdditions.postInit(GregicAdditions.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_65, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1351525304 bytes (1288 MB) / 5021630464 bytes (4789 MB) up to 7492075520 bytes (7145 MB)
	JVM Flags: 4 total; -Xmx8037m -Xms256m -XX:PermSize=256m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2760 Optifine OptiFine_1.12.2_HD_U_E2 129 mods loaded, 129 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                    | Version              | Source                                               | Signature                                |
	|:------ |:------------------------------------- |:-------------------- |:---------------------------------------------------- |:---------------------------------------- |
	| UCHIJ  | minecraft                             | 1.12.2               | minecraft.jar                                        | None                                     |
	| UCHIJ  | mcp                                   | 9.42                 | minecraft.jar                                        | None                                     |
	| UCHIJ  | FML                                   | 8.0.99.99            | forge-1.12.2-14.23.4.2760.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ  | forge                                 | 14.23.4.2760         | forge-1.12.2-14.23.4.2760.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ  | micdoodlecore                         |                      | minecraft.jar                                        | None                                     |
	| UCHIJ  | mdxlib                                | 3.0.0.3              | [1.12.2][3.0.0.3] mdxlib.jar                         | None                                     |
	| UCHIJ  | securitycraft                         | v1.8.7               | [1.12.x] SecurityCraft v1.8.7.jar                    | None                                     |
	| UCHIJ  | aether_legacy                         | 1.12.2-v3.2          | aether_legacy-1.12.2-v3.2.jar                        | None                                     |
	| UCHIJ  | aether_legacy_addon                   | 1.12.2-v1.0          | aether_legacy_addon_1.12.2-v1.0.jar                  | None                                     |
	| UCHIJ  | avp                                   | 6.0.0.7              | aliensvspredator-6.0.0.7.jar                         | None                                     |
	| UCHIJ  | animalium                             | 0.3.7                | Animalium-0.3.7.jar                                  | None                                     |
	| UCHIJ  | antiqueatlas                          | 4.4.9                | antiqueatlas-1.12.2-4.4.9.jar                        | None                                     |
	| UCHIJ  | antiqueatlasoverlay                   | 1.2                  | antiqueatlas-1.12.2-4.4.9.jar                        | None                                     |
	| UCHIJ  | examplemod                            | 1.0                  | antiqueatlas-1.12.2-4.4.9.jar                        | None                                     |
	| UCHIJ  | aquaculture                           | 1.6.6                | Aquaculture-1.12.2-1.6.6.jar                         | None                                     |
	| UCHIJ  | astikoor                              | 1.1.1                | astikoor_horse-carts-1.1.1.jar                       | None                                     |
	| UCHIJ  | bdlib                                 | 1.14.3.12            | bdlib-1.14.3.12-mc1.12.2.jar                         | None                                     |
	| UCHIJ  | betterfoliage                         | 2.1.10               | BetterFoliage-MC1.12-2.1.10.jar                      | None                                     |
	| UCHIJ  | bibliocraft                           | 2.4.5                | BiblioCraft[v2.4.5][MC1.12.2].jar                    | None                                     |
	| UCHIJ  | buildcraftlib                         | 7.99.18              | buildcraft-7.99.18.jar                               | None                                     |
	| UCHIJ  | buildcraftcore                        | 7.99.18              | buildcraft-7.99.18.jar                               | None                                     |
	| UCHIJ  | buildcraftenergy                      | 7.99.18              | buildcraft-7.99.18.jar                               | None                                     |
	| UCHIJ  | ic2                                   | 2.8.73-ex112         | industrialcraft-2-2.8.73-ex112.jar                   | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJ  | jei                                   | 4.11.0.212           | jei_1.12.2-4.11.0.212.jar                            | None                                     |
	| UCHIJ  | mantle                                | 1.12-1.3.2.24        | Mantle-1.12-1.3.2.24.jar                             | None                                     |
	| UCHIJ  | natura                                | 1.12.2-4.3.2.62      | natura-1.12.2-4.3.2.62.jar                           | None                                     |
	| UCHIJ  | forestry                              | 5.8.1.322            | forestry_1.12.2-5.8.1.322.jar                        | None                                     |
	| UCHIJ  | binniecore                            | 2.5.0.168            | binnie-mods-1.12.2-2.5.0.168.jar                     | None                                     |
	| UCHIJ  | binniedesign                          | 2.5.0.168            | binnie-mods-1.12.2-2.5.0.168.jar                     | None                                     |
	| UCHIJ  | genetics                              | 2.5.0.168            | binnie-mods-1.12.2-2.5.0.168.jar                     | None                                     |
	| UCHIJ  | botany                                | 2.5.0.168            | binnie-mods-1.12.2-2.5.0.168.jar                     | None                                     |
	| UCHIJ  | extrabees                             | 2.5.0.168            | binnie-mods-1.12.2-2.5.0.168.jar                     | None                                     |
	| UCHIJ  | extratrees                            | 2.5.0.168            | binnie-mods-1.12.2-2.5.0.168.jar                     | None                                     |
	| UCHIJ  | biomesoplenty                         | 7.0.1.2399           | BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar        | None                                     |
	| UCHIJ  | bookshelf                             | 2.3.559              | Bookshelf-1.12.2-2.3.559.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJ  | buildcraftbuilders                    | 7.99.18              | buildcraft-7.99.18.jar                               | None                                     |
	| UCHIJ  | buildcraftfactory                     | 7.99.18              | buildcraft-7.99.18.jar                               | None                                     |
	| UCHIJ  | buildcraftrobotics                    | 7.99.18              | buildcraft-7.99.18.jar                               | None                                     |
	| UCHIJ  | buildcrafttransport                   | 7.99.18              | buildcraft-7.99.18.jar                               | None                                     |
	| UCHIJ  | buildcraftsilicon                     | 7.99.18              | buildcraft-7.99.18.jar                               | None                                     |
	| UCHIJ  | buildcraftcompat                      | 7.99.15              | buildcraft-compat-7.99.15.jar                        | None                                     |
	| UCHIJ  | chameleon                             | 1.12-4.1.3           | Chameleon-1.12-4.1.3.jar                             | None                                     |
	| UCHIJ  | ctm                                   | MC1.12.2-0.3.2.18    | CTM-MC1.12.2-0.3.2.18.jar                            | None                                     |
	| UCHIJ  | chisel                                | MC1.12.2-0.2.1.35    | Chisel-MC1.12.2-0.2.1.35.jar                         | None                                     |
	| UCHIJ  | codechickenlib                        | 3.2.2.353            | CodeChickenLib-1.12.2-3.2.2.353-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJ  | compactsolars                         | 1.12.2-5.0.17.340    | CompactSolars-1.12.2-5.0.17.340-universal.jar        | None                                     |
	| UCHIJ  | corail_pillar_extension_biomesoplenty | 4.0.1                | corail_pillar_extension_biomesoplenty-4.0.1-1.12.jar | None                                     |
	| UCHIJ  | corail_pillar_extension_chisel        | 4.0.0                | corail_pillar_extension_chisel-4.0.0-1.12.jar        | None                                     |
	| UCHIJ  | coralreef                             | 2.0                  | CoralReef-2.5-1.12.2.jar                             | None                                     |
	| UCHIJ  | customspawner                         | 3.11.4               | CustomMobSpawner-3.11.4.jar                          | None                                     |
	| UCHIJ  | mocreatures                           | 12.0.5               | DrZharks MoCreatures Mod-12.0.5.jar                  | None                                     |
	| UCHIJ  | dynamiclights                         | 1.4.9                | DynamicLights-1.12.2.jar                             | None                                     |
	| UCHIJ  | dynamiclights_onfire                  | 1.0.7                | DynamicLights-1.12.2.jar                             | None                                     |
	| UCHIJ  | dynamiclights_creepers                | 1.0.6                | DynamicLights-1.12.2.jar                             | None                                     |
	| UCHIJ  | dynamiclights_dropitems               | 1.1.0                | DynamicLights-1.12.2.jar                             | None                                     |
	| UCHIJ  | dynamiclights_entityclasses           | 1.0.1                | DynamicLights-1.12.2.jar                             | None                                     |
	| UCHIJ  | dynamiclights_mobequipment            | 1.1.0                | DynamicLights-1.12.2.jar                             | None                                     |
	| UCHIJ  | dynamiclights_flamearrows             | 1.0.1                | DynamicLights-1.12.2.jar                             | None                                     |
	| UCHIJ  | dynamiclights_floodlights             | 1.0.3                | DynamicLights-1.12.2.jar                             | None                                     |
	| UCHIJ  | dynamiclights_otherplayers            | 1.0.9                | DynamicLights-1.12.2.jar                             | None                                     |
	| UCHIJ  | dynamiclights_theplayer               | 1.1.3                | DynamicLights-1.12.2.jar                             | None                                     |
	| UCHIJ  | galacticraftcore                      | 4.0.1.181            | GalacticraftCore-1.12.2-4.0.1.181.jar                | None                                     |
	| UCHIJ  | dsurround                             | 3.4.9.16             | DynamicSurroundings-1.12.2-3.4.9.16.jar              | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UCHIJ  | presets                               | 3.4.9.16             | DynamicSurroundings-1.12.2-3.4.9.16.jar              | None                                     |
	| UCHIJ  | eplus                                 | 5.0.169              | EnchantingPlus-1.12.2-5.0.169.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJ  | galacticraftplanets                   | 4.0.1.181            | Galacticraft-Planets-1.12.2-4.0.1.181.jar            | None                                     |
	| UCHIJ  | mjrlegendslib                         | 1.12.2-1.1.5         | MJRLegendsLib-1.12.2-1.1.5.jar                       | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCHIJ  | extraplanets                          | 1.12.2-0.4.3         | ExtraPlanets-1.12.2-0.4.3.jar                        | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCHIJ  | shadowmc                              | 3.8.0                | ShadowMC-1.12-3.8.0.jar                              | None                                     |
	| UCHIJ  | extrarails                            | 1.3.0                | ExtraRails-1.12-1.3.0.jar                            | None                                     |
	| UCHIJ  | fenceoverhaul                         | 1.3.4                | FenceOverhaul-1.3.4.jar                              | None                                     |
	| UCHIJ  | forgelin                              | 1.7.4                | Forgelin-1.7.4.jar                                   | None                                     |
	| UCHIJ  | forgemultipartcbe                     | 2.5.0.71             | ForgeMultipart-1.12.2-2.5.0.71-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJ  | microblockcbe                         | 2.5.0.71             | ForgeMultipart-1.12.2-2.5.0.71-universal.jar         | None                                     |
	| UCHIJ  | minecraftmultipartcbe                 | 2.5.0.71             | ForgeMultipart-1.12.2-2.5.0.71-universal.jar         | None                                     |
	| UCHIJ  | gardenstuff                           | 1.12-2.1.1           | GardenStuff-1.12-2.1.1.jar                           | None                                     |
	| UCHIJ  | gendustry                             | 1.6.5.8              | gendustry-1.6.5.8-mc1.12.2.jar                       | None                                     |
	| UCHIJ  | gregtech                              | 0.5.9.88             | gregtech-1.12.2-0.5.9.88.jar                         | None                                     |
	| UCHIEE | gtadditions                           | 1.12.2-1.1.0         | GregicAdditions-1.12.2-1.1.0.jar                     | None                                     |
	| UCHI   | mcjtylib_ng                           | 3.0.5                | mcjtylib-1.12-3.0.5.jar                              | None                                     |
	| UCHI   | immcraft                              | 1.5.0                | immcraft-1.12-1.5.0.jar                              | None                                     |
	| UCHI   | twilightforest                        | 3.8.689              | twilightforest-1.12.2-3.8.689-universal.jar          | None                                     |
	| UCHI   | immersiveengineering                  | 0.12-85              | ImmersiveEngineering-0.12-85.jar                     | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHI   | immersivepetroleum                    | 1.1.9                | immersivepetroleum-1.12.2-1.1.9.jar                  | None                                     |
	| UCHI   | trackapi                              | 1.1                  | TrackAPI-1.1_1.12.jar                                | None                                     |
	| UCHI   | immersiverailroading                  | 1.3.3                | ImmersiveRailroading-1.3.3_1.12.jar                  | None                                     |
	| UCHI   | immersivetech                         | 1.3.10               | immersivetech-1.12-1.3.10.jar                        | None                                     |
	| UCHI   | harvestcraft                          | 1.12.2z              | Pam's HarvestCraft 1.12.2z.jar                       | None                                     |
	| UCHI   | jehc                                  | 1.12.2               | JEHC-1.12.2-1.6.1.0.jar                              | None                                     |
	| UCHI   | jarm                                  | 1.1.1                | Just A Raft Mod-1.1.1.jar                            | None                                     |
	| UCHI   | lycanitesmobs                         | 1.20.4.0 - MC 1.12.2 | LycanitesMobsComplete 1.20.4.0 [1.12.2]-1.0.jar      | None                                     |
	| UCHI   | arcticmobs                            | 1.20.4.0 - MC 1.12.2 | LycanitesMobsComplete 1.20.4.0 [1.12.2]-1.0.jar      | None                                     |
	| UCHI   | demonmobs                             | 1.20.4.0 - MC 1.12.2 | LycanitesMobsComplete 1.20.4.0 [1.12.2]-1.0.jar      | None                                     |
	| UCHI   | desertmobs                            | 1.20.4.0 - MC 1.12.2 | LycanitesMobsComplete 1.20.4.0 [1.12.2]-1.0.jar      | None                                     |
	| UCHI   | elementalmobs                         | 1.20.4.0 - MC 1.12.2 | LycanitesMobsComplete 1.20.4.0 [1.12.2]-1.0.jar      | None                                     |
	| UCHI   | forestmobs                            | 1.20.4.0 - MC 1.12.2 | LycanitesMobsComplete 1.20.4.0 [1.12.2]-1.0.jar      | None                                     |
	| UCHI   | freshwatermobs                        | 1.20.4.0 - MC 1.12.2 | LycanitesMobsComplete 1.20.4.0 [1.12.2]-1.0.jar      | None                                     |
	| UCHI   | infernomobs                           | 1.20.4.0 - MC 1.12.2 | LycanitesMobsComplete 1.20.4.0 [1.12.2]-1.0.jar      | None                                     |
	| UCHI   | junglemobs                            | 1.20.4.0 - MC 1.12.2 | LycanitesMobsComplete 1.20.4.0 [1.12.2]-1.0.jar      | None                                     |
	| UCHI   | mountainmobs                          | 1.20.4.0 - MC 1.12.2 | LycanitesMobsComplete 1.20.4.0 [1.12.2]-1.0.jar      | None                                     |
	| UCHI   | plainsmobs                            | 1.20.4.0 - MC 1.12.2 | LycanitesMobsComplete 1.20.4.0 [1.12.2]-1.0.jar      | None                                     |
	| UCHI   | saltwatermobs                         | 1.20.4.0 - MC 1.12.2 | LycanitesMobsComplete 1.20.4.0 [1.12.2]-1.0.jar      | None                                     |
	| UCHI   | shadowmobs                            | 1.20.4.0 - MC 1.12.2 | LycanitesMobsComplete 1.20.4.0 [1.12.2]-1.0.jar      | None                                     |
	| UCHI   | swampmobs                             | 1.20.4.0 - MC 1.12.2 | LycanitesMobsComplete 1.20.4.0 [1.12.2]-1.0.jar      | None                                     |
	| UCHI   | malisiscore                           | 1.12.2-6.4.0         | malisiscore-1.12.2-6.4.0.jar                         | None                                     |
	| UCHI   | malisisdoors                          | 1.12.2-7.3.0         | malisisdoors-1.12.2-7.3.0.jar                        | None                                     |
	| UCHI   | minecolonies                          | 1.12.2-0.9.4-RELEASE | minecolonies-1.12.2-0.9.4-RELEASE-universal.jar      | None                                     |
	| UCHI   | numina                                | 1.10.0               | ModularPowersuits-1.12.2-0.3.0.8.jar                 | None                                     |
	| UCHI   | powersuits                            | 1.12.2-0.3.0.8       | ModularPowersuits-1.12.2-0.3.0.8.jar                 | None                                     |
	| UCHI   | morebees                              | 1.12.2-2.0.1         | morebees-1.12.2-2.0.1.jar                            | None                                     |
	| UCHI   | mrtjpcore                             | 2.1.3.35             | MrTJPCore-1.12.2-2.1.3.35-universal.jar              | None                                     |
	| UCHI   | nei                                   | 2.4.1                | NotEnoughItems-1.12.2-2.4.1.238-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHI   | nuclearcraft                          | 2.11g                | NuclearCraft-2.11g--1.12.2.jar                       | None                                     |
	| UCHI   | orbis_api                             | 1.12.2-1.1.91        | orbis_api-1.12.2-1.1.91.jar                          | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| UCHI   | projectred-core                       | 4.9.1.92             | ProjectRed-1.12.2-4.9.1.92-Base.jar                  | None                                     |
	| UCHI   | projectred-compat                     | 1.0                  | ProjectRed-1.12.2-4.9.1.92-compat.jar                | None                                     |
	| UCHI   | projectred-integration                | 4.9.1.92             | ProjectRed-1.12.2-4.9.1.92-integration.jar           | None                                     |
	| UCHI   | projectred-transmission               | 4.9.1.92             | ProjectRed-1.12.2-4.9.1.92-integration.jar           | None                                     |
	| UCHI   | projectred-fabrication                | 4.9.1.92             | ProjectRed-1.12.2-4.9.1.92-fabrication.jar           | None                                     |
	| UCHI   | projectred-expansion                  | 4.9.1.92             | ProjectRed-1.12.2-4.9.1.92-mechanical.jar            | None                                     |
	| UCHI   | projectred-relocation                 | 4.9.1.92             | ProjectRed-1.12.2-4.9.1.92-mechanical.jar            | None                                     |
	| UCHI   | projectred-transportation             | 4.9.1.92             | ProjectRed-1.12.2-4.9.1.92-mechanical.jar            | None                                     |
	| UCHI   | projectred-exploration                | 4.9.1.92             | ProjectRed-1.12.2-4.9.1.92-world.jar                 | None                                     |
	| UCHI   | roguelike                             | 1.8.0                | RoguelikeDungeons-1.12.2-1.8.0.jar                   | None                                     |
	| UCHI   | treechopper                           | 1.2.4                | TreeChopper-1.12.2-1.2.4.jar                         | None                                     |
	| UCHI   | zoocraftdiscoveries                   | 1.0                  | Zoocraft Discoveries 1.12.2-1.2.0.jar                | None                                     |
	| UCHI   | llibrary                              | 1.7.15               | llibrary-1.7.15-1.12.2.jar                           | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UCHI   | jurassicraft                          | 2.1.17               | JurassiCraft-1.12.2-2.1.17.jar                       | None                                     |
	| UCHI   | corail_pillar                         | 4.1.0                | corail_pillar-4.1.0-1.12.jar                         | None                                     |

	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
ForgelinPlugin (Forgelin-1.7.4.jar)
  
CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  team.chisel.ctm.client.asm.CTMTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-85.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
FMLModule ([1.12.2][3.0.0.3] mdxlib.jar)
  com.arisux.mdx.AccessTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.16.jar)
  org.blockartistry.DynSurround.asm.Transformer
DLFMLCorePlugin (DynamicLights-1.12.2.jar)
  atomicstryker.dynamiclights.common.DLTransformer
llibrary (llibrary-core-1.0.8-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 358.87' Renderer: 'GeForce GTX 660M/PCIe/SSE2'
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	List of loaded APIs: 
		* AetherAPI (v1.0.0) from aether_legacy-1.12.2-v3.2.jar
		* antiqueatlasapi (5.1) from antiqueatlas-1.12.2-4.4.9.jar
		* AVPAPI (1.0.0) from aliensvspredator-6.0.0.7.jar
		* BuildCraftAPI|blocks (1.0) from buildcraft-7.99.18.jar
		* BuildCraftAPI|boards (2.0) from buildcraft-7.99.18.jar
		* BuildCraftAPI|core (2.2) from buildcraft-7.99.18.jar
		* BuildCraftAPI|crops (1.1) from buildcraft-7.99.18.jar
		* BuildCraftAPI|enums (1.0) from buildcraft-7.99.18.jar
		* BuildCraftAPI|events (2.0) from buildcraft-7.99.18.jar
		* BuildCraftAPI|facades (1.1) from buildcraft-7.99.18.jar
		* BuildCraftAPI|filler (5.0) from buildcraft-7.99.18.jar
		* BuildCraftAPI|fuels (2.0) from buildcraft-7.99.18.jar
		* BuildCraftAPI|gates (4.1) from buildcraft-7.99.18.jar
		* BuildCraftAPI|items (1.1) from buildcraft-7.99.18.jar
		* BuildCraftAPI|library (2.0) from buildcraft-7.99.18.jar
		* BuildCraftAPI|lists (1.0) from buildcraft-7.99.18.jar
		* BuildCraftAPI|power (1.3) from buildcraft-7.99.18.jar
		* BuildCraftAPI|recipes (3.0) from buildcraft-7.99.18.jar
		* BuildCraftAPI|robotics (3.0) from buildcraft-7.99.18.jar
		* BuildCraftAPI|statements (1.1) from buildcraft-7.99.18.jar
		* BuildCraftAPI|tiles (1.2) from buildcraft-7.99.18.jar
		* BuildCraftAPI|tools (1.0) from buildcraft-7.99.18.jar
		* BuildCraftAPI|transport (5.0) from buildcraft-7.99.18.jar
		* Chisel-API (0.0.1) from Chisel-MC1.12.2-0.2.1.35.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.12.2-0.2.1.35.jar
		* ctm-api (0.1.0) from CTM-MC1.12.2-0.3.2.18.jar
		* ctm-api-events (0.1.0) from CTM-MC1.12.2-0.3.2.18.jar
		* ctm-api-models (0.1.0) from CTM-MC1.12.2-0.3.2.18.jar
		* ctm-api-textures (0.1.0) from CTM-MC1.12.2-0.3.2.18.jar
		* ctm-api-utils (0.1.0) from CTM-MC1.12.2-0.3.2.18.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|arboriculture (4.3.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|book (5.8.1) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|climate (5.0.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|core (5.7.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|farming (5.8.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|food (1.1.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|genetics (5.7.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|gui (5.8.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|lepidopterology (1.4.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|modules (5.7.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|world (2.1.0) from forestry_1.12.2-5.8.1.322.jar
		* Galacticraft API (1.2) from GalacticraftCore-1.12.2-4.0.1.181.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.5.8-mc1.12.2.jar
		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.12-85.jar
		* ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.12-85.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.11.0.212.jar
		* projectred|api (2.0) from ProjectRed-1.12.2-4.9.1.92-Base.jar
		* SecurityCraftAPI (1.2.2) from [1.12.x] SecurityCraft v1.8.7.jar
	OptiFine Version: OptiFine_1.12.2_HD_U_E2
	OptiFine Build: 20180728-185429
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 358.87
	OpenGlRenderer: GeForce GTX 660M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by ScienceDrummer** [comment] 2018-09-29 15:18
Can confirm, got same crash. https://paste.dimdev.org/icalucipav.mccrash

**Comment by Bartz24** [comment] 2018-09-30 23:11
Ok. So the issue hasn't been fixed, but in the next version (released in the near future), the game will not crash, but will still give the error in the log, along with the message "The fluid **X** failed to do something with getFilledCell".

Also, if you see a water cell in a recipe that doesn't make sense, that's also a sign of when the error occured.

If you see either of these signs, let us know with the exact error, or the recipe details.

**Comment by EmosewaPixel** [comment] 2018-10-01 06:55
Duplicate of #1

**Closed** 2018-10-01 17:41 UTC
Labels: duplicate, fixed in the next version
